### ISSUE TITLE
Shuttle.Core.Json should have a dependency to the Newtonsoft.Json package

### ISSUE THREAD

**Issue by zgabi** [Shuttle/Shuttle.Core.Json#1]
Newtonsoft.Json is not installed automatically when I add Shuttle.Core.Json to my project.
Probably the problem is the missing dependency.

https://www.nuget.org/packages/Shuttle.Core.Json/ shows: "This package has no dependencies."

**Comment by eben-roux** [comment]
Thanks for letting me know.

I have created a new release:
- https://www.nuget.org/packages/Shuttle.Core.Json/
- https://github.com/Shuttle/Shuttle.Core.Json/releases/tag/v1.0.1
